repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
     -   id: autopep8
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.2
    hooks:
    -   id: isort
        args: [--atomic]
        types: [python]
        verbose: true
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
